# Generated by Django 2.2.12 on 2020-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('crsid', models.CharField(max_length=10)),
                ('position', models.CharField(choices=[('MC', "Men's Captain"), ('WC', "Women's Captain"), ('MS', "Men's Secretary"), ('WS', "Women's Secretary"), ('WO', 'Welfare Officer'), ('JT', 'Junior Treasurer'), ('SS', 'Social Secretary'), ('W', 'Webmaster')], default='W', max_length=2)),
                ('committee_start_year', models.IntegerField(default=2020)),
                ('course', models.TextField(blank=True)),
                ('college', models.TextField(blank=True)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('started_fives', models.TextField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
