# Generated by Django 2.2.11 on 2020-05-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('About', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
