# Generated by Django 2.2.12 on 2020-08-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_newalbumphoto_light_box_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newalbumphoto',
            name='light_box_index',
            field=models.IntegerField(default=0),
        ),
    ]
