# Generated by Django 2.2.12 on 2020-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamnews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(choices=[('SAFETY', 'Safety Statement'), ('WELFARE', 'Welfare Policy'), ('PRIVACY', 'Privacy Notice'), ('CONDUCT', 'Code of Conduct'), ('CONSTITUTION', 'Constitution')], default='WELFARE', max_length=15)),
                ('file', models.FileField(upload_to='documents/')),
                ('start_year', models.IntegerField(default=2020)),
            ],
        ),
    ]
