# Generated by Django 2.2.12 on 2020-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EtonFivesatCambridge', models.TextField(default='type text here')),
                ('WhatisEtonFives', models.TextField(default='type text here')),
                ('HistoryofEtonFives', models.TextField(default='type text here')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeNeedSponsors', models.TextField(default='type text here')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTheClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlsDonate_intro', models.TextField(default='type text here')),
                ('PlsDonate_middle', models.TextField(default='type text here')),
                ('PlsDonate_end', models.TextField(default='type text here')),
                ('DonationLink', models.TextField(default='this is the link to the donation portal')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Training', models.TextField(default='type text here')),
                ('Beginners', models.TextField(default='type text here')),
            ],
        ),
    ]
