# Generated by Django 2.2.12 on 2020-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitetext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='CalendarLink',
            field=models.TextField(default='this is the link to the match calendar'),
        ),
    ]
