# Generated by Django 2.2.12 on 2020-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitetext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfives',
            name='EtonFivesatCambridge',
            field=models.TextField(default='type text here'),
        ),
        migrations.AlterField(
            model_name='aboutfives',
            name='HistoryofEtonFives',
            field=models.TextField(default='type text here'),
        ),
        migrations.AlterField(
            model_name='aboutfives',
            name='WhatisEtonFives',
            field=models.TextField(default='type text here'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Beginners',
            field=models.TextField(default='type text here'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Training',
            field=models.TextField(default='type text here'),
        ),
    ]
