# Generated by Django 2.2.12 on 2020-08-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitetext', '0002_training_calendarlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SignUpForNewsLetter', models.TextField(default='this is the link to the google form to sign up')),
            ],
        ),
    ]
